### ISSUE TITLE
Deploy auto from travis to GH

### ISSUE THREAD

**Issue by adriens** [adriens/schemacrawler-deb#2]

**Comment by adriens** [comment]
For now, it's failing :

`Installing deploy dependencies

Fetching: addressable-2.3.8.gem (100%)

Successfully installed addressable-2.3.8

Fetching: multipart-post-2.0.0.gem (100%)

Successfully installed multipart-post-2.0.0

Fetching: faraday-0.9.2.gem (100%)

Successfully installed faraday-0.9.2

Fetching: sawyer-0.6.0.gem (100%)

Successfully installed sawyer-0.6.0

Fetching: octokit-4.2.0.gem (100%)

Successfully installed octokit-4.2.0

5 gems installed

Fetching: mime-types-2.99.gem (100%)

Successfully installed mime-types-2.99

1 gem installed

dpl.2

Preparing deploy

Logged in as SALES

Deploying to repo: adriens/schemacrawler-deb

remote: Counting objects: 180, done.

remote: Compressing objects: 100% (67/67), done.

remote: Total 180 (delta 101), reused 174 (delta 96), pack-reused 0

Receiving objects: 100% (180/180), 17.57 KiB | 0 bytes/s, done.

Resolving deltas: 100% (101/101), completed with 10 local objects.

From https://github.com/adriens/schemacrawler-deb
- [new tag]         10.10.05   -> 10.10.05
- [new tag]         11.01.01   -> 11.01.01
- [new tag]         11.02.01   -> 11.02.01
- [new tag]         12.01.01   -> 12.01.01
- [new tag]         12.02.01   -> 12.02.01
- [new tag]         12.02.02   -> 12.02.02
- [new tag]         12.02.03   -> 12.02.03
- [new tag]         12.03.01   -> 12.03.01

Current tag is: 

dpl.3

Deploying application

/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/adriens/schemacrawler-deb/releases: 422 - Validation Failed (Octokit::UnprocessableEntity)

Error summary:

  resource: Release

  code: missing_field

  field: tag_name

  resource: Release

  code: custom

  field: tag_name

  message: tag_name is not well-formed

  resource: Release

  code: custom

  message: Published releases must have a valid tag // See: https://developer.github.com/v3/repos/releases/#create-a-release

```
from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/connection.rb:154:in `request'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/connection.rb:28:in `post'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/client/releases.rb:32:in `create_release'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider/releases.rb:99:in `push_app'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider.rb:145:in `block in deploy'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/cli.rb:41:in `fold'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/provider.rb:145:in `deploy'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/cli.rb:32:in `run'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/lib/dpl/cli.rb:7:in `run'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.11/bin/dpl:5:in `<top (required)>'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'

from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
```

failed to deploy`

**Comment by adriens** [comment]
Using https://github.com/travis-ci/travis-ci/issues/1675

**Comment by adriens** [comment]
It works !!! See the auto-attached .deb : https://github.com/adriens/schemacrawler-deb/releases/tag/14.05.05

**Comment by adriens** [comment]
Done.
